interface DesignToolProps {
    path:string;
    alt:string;
}

export const designTools:DesignToolProps[] = [
    {
        path:'/design/1.jpg',
        alt:'1'
    },
    {
        path:'/design/2.jpg',
        alt:'2'
    },
    {
        path:'/design/3.jpg',
        alt:'3'
    },
    {
        path:'/design/4.jpg',
        alt:'4'
    },
    {
        path:'/design/5.jpg',
        alt:'5'
    },
    {
        path:'/design/6.jpg',
        alt:'6'
    },
    {
        path:'/design/7.jpg',
        alt:'7'
    },
    {
        path:'/design/8.jpg',
        alt:'8'
    }
]